# © Copyright IBM Corporation 2015, 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ibmcom/mq
USER 0
RUN mkdir -p /etc/mqm/mft
COPY *.mqsc /etc/mqm/mft/ 
COPY *.sh /etc/mqm/mft/ 
COPY mq.htpasswd /etc/mqm
RUN chmod 0660 /etc/mqm/mft/*.*
RUN chmod +x /etc/mqm/mft/*.sh
RUN chmod 0660 /etc/mqm/mq.htpasswd
USER 1001