kind: Deployment
apiVersion: apps/v1
metadata:
  name: dest-agent
  namespace: ibm-mqmft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dest-agent
  template:
    metadata:
      labels:
        app: dest-agent
        deploymentconfig: dest-agent
    spec:
      volumes:
        - name: dest-agent-config-map
          configMap:
            name: dest-agent-config
            defaultMode: 420
        - name: dest-volume
          persistentVolumeClaim:
            claimName: pvc-dest
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - agentready
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /mnt/termination-log
          name: dest
          livenessProbe:
            exec:
              command:
                - agentalive
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MFT_AGENT_NAME
              value: DEST
            - name: LICENSE
              value: accept
            - name: MFT_AGENT_CONFIG_FILE
              value: /mqmftcfg/agentconfig/destagent.json
            - name: MFT_MOUNT_PATH
              value: /mountpath
            - name: MFT_AGENT_DISPLAY_CAPTURE_LOG
              value: "yes"
            - name: BFG_JVM_PROPERTIES
              value: -Djava.util.prefs.systemRoot=/jprefs/.java/.systemPrefs -Djava.util.prefs.userRoot=/jprefs/.java/.userPrefs
          imagePullPolicy: Always
          volumeMounts:
            - name: dest-agent-config-map
              mountPath: /mqmftcfg/agentconfig
            - name: dest-volume
              mountPath: /mountpath
          terminationMessagePolicy: File
          image: >-
              icr.io/ibm-messaging/mqmft:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler