kind: ConfigMap
apiVersion: v1
metadata:
  name: dest-agent-config
  namespace: ibm-mqmft
data:
  destagent.json: > 
    "{"waitTimeToStart":20,"coordinationQMgr":{"name":"MFTQM","host":"mftqm-ibm-mq.ibm-mqmft.svc.cluster.local","port":1414,"channel":"QS_SVRCONN","additionalProperties":{}},"commandQMgr":{"name":"MFTQM","host":"mftqm-ibm-mq.ibm-mqmft.svc.cluster.local","port":1414,"channel":"QS_SVRCONN","additionalProperties":{}},"agents":[{"name":"DEST","deleteOnTermination":"true","type":"STANDARD","qmgrName":"MFTQM","qmgrHost":"mftqm-ibm-mq.ibm-mqmft.svc.cluster.local","qmgrPort":1414,"qmgrChannel":"QS_SVRCONN","additionalProperties":{"enableQueueInputOutput":"true","trace":"all","logCapture":"true"}}]}"
